New sign up confirmation logic
littlepony99/wax-deals pull request #11
Opened 2021-08-12 08:24 UTC by Greengrer

2021-08-12 11:48 UTC, TarasOrlovskyi commented on src/main/java/com/vinylteam/vinyl/web/controller/RestSignupController.java
> +                "message", s);
please, rename 's'

2021-08-13 08:59 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/exception/entity/EmailConfirmationErrors.java
> +    TOKEN_FROM_LINK_NOT_FOUND("your link isn't correct. Please, try again or contact us"),
your not Your?

2021-08-13 09:04 UTC, hemiSRT8 requested changes

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenStorageService.java
> +                        return l1;
magic number

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenStorageService.java
> +                        return l1;
magic number

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenStorageService.java
> +                        return 1_000_000_000L * (localDateTime.toEpochSecond(offset) - LocalDateTime.now().toEpochSecond(offset));
magic number

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenStorageService.java
> +                .expireAfter(new Expiry<String, LocalDateTime>() {
Encapsulate these into private method and use method's reference instead

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/JwtTokenProvider.java
> +            return true && !tokenStorageService.isTokenBlocked(token);
really?

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/JwtTokenProvider.java
> +                .atZone(ZoneId.systemDefault())
why system default not exact zone?

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultEmailConfirmationService.java
> +
obsolete extra line

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultUserService.java
> +/*        if (!userToCheckAgainst.getStatus()) {
YAGNI

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/EmailConfirmationController.java
> +
Obsolete extra lines

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/SignInController.java
> +//@Controller
YAGNI

2021-08-13 09:04 UTC, hemiSRT8 commented on src/main/resources/application.properties
> +FILTER_LEVEL=debug
sure?

2021-08-13 11:41 UTC, hemiSRT8 requested changes

2021-08-13 11:41 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/handler/ApiExceptionHandler.java
>  //@ControllerAdvice
YAGNI

2021-08-13 11:41 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/web/controller/SignupControllerITest.java
> +class RestSignupControllerITest {
without REST

2021-08-13 12:43 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenStorageService.java
> +                        return l1;
code from previous PR

2021-08-13 12:43 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/web/controller/EmailConfirmationController.java
> +
code from previous PR

2021-08-13 12:44 UTC, littlepony99 approved these changes

2021-08-13 12:45 UTC, hemiSRT8 approved these changes

2021-08-13 12:52 UTC, merged