Release 13082021
littlepony99/wax-deals pull request #12
Opened 2021-08-16 07:49 UTC by TEdwardJ

2021-08-17 11:12 UTC, hemiSRT8 requested changes

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/dao/jdbc/JdbcUserDao.java
> +        return id;
obsolete variable declaration

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/dao/jdbc/extractor/UserMapper.java
> +    )
obsolete line break
should be })

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/dao/jdbc/extractor/UserMapper.java
> +        ArrayList<SimpleGrantedAuthority> list = new ArrayList<>();
Could be written in one line
Either java.util.List.of(...) or guava's Lists.newArrayList(...);

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/entity/JwtUser.java
> +public class JwtUser implements UserDetails {
Can we use Lombok for pojo staff?

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/SecurityConfiguration.java
> +        web.ignoring().antMatchers(
one line

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/SecurityConfiguration.java
> +/*    @Bean
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/SecurityConfiguration.java
> +                //.sessionManagement()
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/SecurityService.java
> +    void setEncoder(PasswordEncoder encoder);
Why do we need setter injection here not field one?

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultEmailConfirmationService.java
> +        UUID uuid = UUID.randomUUID();
one line

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultOneVinylOffersService.java
> +        // 1 prepare offers -- validate and parse
Your code should be self-descriptive
Please remove comments

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultOneVinylOffersService.java
> +        // 2 add artists vinyls to searchable vinyl
Your code should be self-descriptive
Please remove comments

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultUniqueVinylService.java
> +        if (vinyl.isHasOffers()) {
hasOffers should be renamed to offers and then getter for boolean should be hasOffers

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultUserService.java
> +        //securityService.emailFormatCheck(email);
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/JwtLoginController.java
> +    public ResponseEntity<UserSecurityResponse> tokenChecking(@RequestHeader(name = "Authorization") String token) {
no present continous in methods naming
checkToken probably

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/OneVinylOfferController.java
> +        UniqueVinyl uniqueVinyl = oneVinylOffersService.getUniqueVinyl(id);
this should be outside controller logic , inside service

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/ProfileController.java
>                                   Model model) {
one line for parameters

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/ProfileController.java
>      public String getEditProfilePage(@SessionAttribute(value = "user", required = false) User user,
one line for parameters

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/SearchResultsController.java
> +    public List<UniqueVinylDto> getSearchResultPage(@RequestParam(value = "matcher") String matcher) {
is this method still returning pages?

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/ShopController.java
> +    public List<ShopDto> getShopPage() {
still returning pages?

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/ShopController.java
> +        List<Shop> shopList = shopService.findAll();
Please rewrite it using streams

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/SignupController.java
> +
obsolete extra line

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/SignupController.java
> +            ResponseEntity<Map<String, Object>> response = new ResponseEntity<>(responseMap, HttpStatus.BAD_REQUEST);
obsolete variable declaration

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/SignupController.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/controller/SignupController.java
> +        User byEmail = userService.findByEmail(username);
obsolete variable declaration

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/LoginRequest.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/OneVinylOfferDto.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/OneVinylPageDto.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/ShopDto.java
> +    private int id;
Integer better

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/ShopDto.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/UniqueVinylDto.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/UserDto.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/UserSecurityResponse.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/dto/UserSecurityResponse.java
> +    String token;
maybe private modifers?

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/filter/JwtValidatorFilter.java
> +        return "/login".equals(path) || "/signIn".equals(path);
Maybe contains instead of equals?

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/filter/SecurityFilter.java
>  public class SecurityFilter implements Filter {
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/web/filter/UserAttributeFilter.java
> +                    var foundUser = (User) userService.findByEmail(principal.getUsername());
obsolete variable declaration

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/dao/jdbc/JdbcConfirmationTokenDaoITest.java
> +/*    @DynamicPropertySource
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/dao/jdbc/JdbcPasswordRecoveryDaoITest.java
> +/*    @DynamicPropertySource
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/dao/jdbc/JdbcShopDaoITest.java
> +/*    @DynamicPropertySource
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/dao/jdbc/JdbcUserDaoITest.java
> +/*    @DynamicPropertySource
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/dao/jdbc/JdbcUserPostDaoITest.java
> +/*    @Container
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/security/impl/SpringSecurityServiceITest.java
> +/*    @Test
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/service/impl/DefaultOneVinylOffersServiceTest.java
> +    private ShopService mockedShopService;
no need to name ot mocked, just offerService
it is clear from @MockBean that it is mocked

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/util/DataGeneratorForTests.java
> +            UniqueVinyl uniqueVinyl = UniqueVinyl.builder()
encapsulate creation of uniqueVinyl into private method

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/web/controller/CatalogControllerTest.java
> +    WebApplicationContext context;
why package private

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/service/impl/DefaultOneVinylOffersServiceTest.java
> +    void getSortedInStockOffersAndShops_whenUniqueVinylHasValidOffers() {
bad method name

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/service/impl/DefaultOneVinylOffersServiceTest.java
> +
YAGNI

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/web/controller/SearchResultsControllerTest.java
> +    WebApplicationContext context;
why package private

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/web/controller/ShopControllerTest.java
> +
obsolete line break

2021-08-17 11:12 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/web/controller/SearchResultsControllerTest.java
> +                        .param("matcher", matcher))
obsolete line break

2021-08-20 07:27 UTC, TEdwardJ commented on src/main/java/com/vinylteam/vinyl/security/SecurityService.java
> +    void setEncoder(PasswordEncoder encoder);
Due to cyclic reference, now it is resolved

2021-08-20 07:27 UTC, TEdwardJ commented on src/main/java/com/vinylteam/vinyl/security/SecurityService.java
> +    void setEncoder(PasswordEncoder encoder);
Due to cyclic reference, now it is resolved

2021-08-23 07:47 UTC, littlepony99 approved these changes

2021-08-23 12:15 UTC, hemiSRT8 approved these changes

2021-08-24 16:13 UTC, merged