Redeyerecords parser
littlepony99/wax-deals pull request #17
Opened 2021-09-06 10:37 UTC by Greengrer

2021-09-06 15:54 UTC, hemiSRT8 approved these changes

2021-09-06 15:54 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +    private static final ParserConfiguration offerParserConfiguration = ParserConfiguration.builder()
encapsulate into private method

2021-09-06 15:54 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +    protected static final String BASE_LINK = "https://www.redeyerecords.co.uk/custom-view/page-1";
private

2021-09-06 15:54 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +        var pageLinks = getDocument(BASE_LINK)
Set<String>

2021-09-06 15:54 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +                .flatMap(page -> this.getDocument(page).stream())
w/o this

2021-09-06 15:58 UTC, hemiSRT8 submitted a review, later dismissed

2021-09-06 15:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +                .map(offerLink -> getRawOfferFromOfferLink(offerLink))
method reference

2021-09-06 15:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +                .filter(rawOffer -> isValid(rawOffer))
method reference

2021-09-06 16:08 UTC, littlepony99 approved these changes, later dismissed

2021-09-13 06:59 UTC, littlepony99 approved these changes, later dismissed

2021-09-13 07:07 UTC, hemiSRT8 requested changes

2021-09-13 07:07 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +    private static final ParserConfiguration offerParserConfiguration = createParserConfiguration();
Please remove this field and use

> private final RedEyeRecordsDetailedParser oneOfferParser = new RedEyeRecordsDetailedParser(createParserConfiguration()); (one line)

2021-09-13 07:07 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/util/impl/RedEyeRecordsParser.java
> +    private static ParserConfiguration createParserConfiguration() {
Please move this method at the bottom of the class

2021-09-16 20:59 UTC, littlepony99 approved these changes

2021-09-21 06:23 UTC, TarasOrlovskyi approved these changes

2021-09-22 07:20 UTC, closed without merging