Password special characters issue fix
littlepony99/wax-deals pull request #19
Opened 2021-09-07 08:40 UTC by Greengrer

2021-09-07 09:25 UTC, hemiSRT8 requested changes

2021-09-07 09:25 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/security/impl/DefaultSecurityServiceTest.java
> +                securityService.hashPassword(passwordToHash.toCharArray(), salt, 10000));
one line

2021-09-07 09:25 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/security/impl/DefaultSecurityServiceTest.java
> +    @DisplayName("Checkes if the result of hashing with 10000 iterations is the same for equal inputs.")
Checks?

2021-09-07 11:31 UTC, shelsoftensy commented on src/main/java/com/vinylteam/vinyl/security/impl/DefaultSecurityService.java
> +        if (!password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]{8,}$")) {
maybe move string to a constant value?

2021-09-07 12:47 UTC, littlepony99 requested changes

2021-09-07 12:47 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/security/impl/DefaultSecurityService.java
> +        if (!password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]{8,}$")) {
maybe move string to a constant value?

2021-09-09 10:58 UTC, hemiSRT8 requested changes

2021-09-09 10:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/impl/DefaultSecurityService.java
> +    private final String passwordValidator = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]{8,}$";
make it static final and name it PASSWORD_PATTERN

2021-09-09 10:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/impl/DefaultSecurityService.java
> +    private final String emailValidator = "/^[^\\s@]+@[^\\s@]+$/";
make it static final and name it EMAIL_PATTERN

2021-09-09 10:58 UTC, hemiSRT8 commented on src/test/java/com/vinylteam/vinyl/security/impl/DefaultSecurityServiceTest.java
> +        assertThrows(IllegalArgumentException.class, () ->
one line

2021-09-10 08:58 UTC, littlepony99 approved these changes

2021-09-13 06:51 UTC, hemiSRT8 approved these changes

2021-09-13 09:12 UTC, merged