Refresh token
littlepony99/wax-deals pull request #20
Opened 2021-09-08 13:39 UTC by TEdwardJ

2021-09-08 13:56 UTC, littlepony99 requested changes

2021-09-08 13:56 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/entity/TokenPair.java
> +    String refreshToken;
add empty row after last class row

2021-09-08 13:56 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/security/LogoutTokenStorageService.java
> +    void storePairIdentifier(String pairIdentifier, LocalDateTime expirationDate);
add empty row after last class row

2021-09-08 13:56 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/security/SecurityConfiguration.java
> +        delegateFilterProxy.setTargetBeanName("jwtValidatorFilter");
move to a constant variable?

2021-09-08 13:56 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/service/DefaultProfileManagementService.java
>          logoutService.logout(request, null, null);
seems to me that its not a good "interface" idea
maybe you should create logout method with 1 param, which under hood will send request logoutService.logout(request, null, null);

2021-09-08 13:56 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/service/JwtService.java
>  }
add empty row after last class row

2021-09-08 13:56 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultUserService.java
> +    private final EmailConfirmationService emailConfirmationService;
add empty row, divide variable and method parts

2021-09-09 11:58 UTC, hemiSRT8 requested changes

2021-09-09 11:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/entity/Currency.java
>  import java.util.Optional;
please remove all logging statements from this enum

2021-09-09 11:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/entity/Currency.java
>  import java.util.Optional;
could you please also check this code?

else if (" EUR".equals(currencyDescription) || "EUR".equals(currencyDescription) || "€".equals(currencyDescription)
                || "&nbsp;€".equals(currencyDescription)) {
            resultingCurrency = EUR;
        }

is white space between " and EUR ok ?

" EUR .."

2021-09-09 11:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/entity/TokenPair.java
> +    String id;
why package-private modifiers?

2021-09-09 11:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/entity/UniqueVinyl.java
> +    private boolean hasOffers;
please revert this
its should be "offers"
we use has* for boolean's getters in this case

2021-09-09 11:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenService.java
>      private Expiry<String, LocalDateTime> getExpirationStrategy() {
please move this private method below public ones

2021-09-09 11:58 UTC, hemiSRT8 commented on src/main/java/com/vinylteam/vinyl/security/InMemoryLogoutTokenService.java
>      private Expiry<String, LocalDateTime> getExpirationStrategy() {
could you please also fix all parameters String s in this class?
you could go to the documentation of com.github.benmanes.caffeine.cache.Expiry and read what s means

2021-09-09 17:22 UTC, TEdwardJ commented on src/main/java/com/vinylteam/vinyl/entity/Currency.java
>  import java.util.Optional;
Yes, I suppose the author wanted to be sure that any possible string with currency will be recognized correctly, but think trim() will be better

2021-09-09 17:23 UTC, TEdwardJ commented on src/main/java/com/vinylteam/vinyl/entity/TokenPair.java
> +    String id;
@FieldDefaults(makeFinal=true, level=AccessLevel.PRIVATE)  - defined in the @Value annotation

2021-09-09 17:25 UTC, TEdwardJ commented on src/main/java/com/vinylteam/vinyl/entity/TokenPair.java
> +    String id;
@FieldDefaults(makeFinal=true, level=AccessLevel.PRIVATE) from @Value annotation from lombok

2021-09-09 17:28 UTC, TEdwardJ commented on src/main/java/com/vinylteam/vinyl/entity/UniqueVinyl.java
> +    private boolean hasOffers;
it requires reloading data to ElasticSearch... or probably there is another solution, but it has to be found. Just renaming makes the catalog page fails

2021-09-13 06:57 UTC, littlepony99 approved these changes

2021-09-13 07:11 UTC, hemiSRT8 approved these changes

2021-09-13 07:21 UTC, merged