Watchlist new
littlepony99/wax-deals pull request #23
Opened 2021-09-19 19:32 UTC by littlepony99

2021-09-24 19:15 UTC, ValentynaBondarenko commented on src/main/java/com/vinylteam/vinyl/discogs4j/client/DiscogsClient.java
>          System.out.println(request.toString());
sout? may you add logs?

2021-09-24 19:15 UTC, ValentynaBondarenko commented on src/main/java/com/vinylteam/vinyl/entity/WantedVinyl.java
> +    private String id;
why do you use **String** id?

2021-09-24 19:15 UTC, ValentynaBondarenko commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCatalogService.java
> +        UniqueVinyl uniqueVinyl = uniqueVinylService.findById(id);
should you add logs in your methods

2021-09-24 19:15 UTC, ValentynaBondarenko commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCatalogService.java
> +    public Shop findOfferShop(List<Shop> shopsList, Offer offer) {
it is method can`t be public

2021-09-24 19:15 UTC, ValentynaBondarenko commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCatalogService.java
> +package com.vinylteam.vinyl.service.impl;
duplicate service

2021-09-26 21:02 UTC, Greengrer requested changes

2021-09-26 21:02 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/discogs4j/client/DiscogsClient.java
>       */
Do we need these comments?

2021-09-26 21:02 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/exception/DiscogsUserNotFoundException.java
> +    }
We already have NotFoundException to send 404. I suggest throwing it in services instead and deleting this class.

2021-09-26 21:02 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/exception/entity/VinylErrors.java
> +
Class name is ambiguous. If this is for discogs wantlist then it's better to call WantlistErrors.
If it's for catalogue/{id} - there's enum CatalogErrors with VINYL_BY_ID_NOT_FOUND.

2021-09-29 07:24 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/service/impl/DefaultCatalogService.java
> +package com.vinylteam.vinyl.service.impl;
if you clone repository, you will not find duplicates for them

2021-09-29 07:24 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/discogs4j/client/DiscogsClient.java
>       */
standart methods doc, added not in this PR

2021-09-29 07:28 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/exception/DiscogsUserNotFoundException.java
> +    }
why you can't check, that front asked for 400 error code for this?
and compare to your "We already have NotFoundException to send 404" ???

2021-09-29 07:45 UTC, Greengrer commented on src/main/java/com/vinylteam/vinyl/exception/DiscogsUserNotFoundException.java
> +    }
Then It would be better called "BadRequestException". Not found exception with code 400 brings confusion

2021-10-04 05:23 UTC, littlepony99 commented on src/main/java/com/vinylteam/vinyl/entity/WantedVinyl.java
> +    private String id;
cause elasticSearch entity should have only String id

2021-10-04 07:23 UTC, Greengrer approved these changes

2021-10-04 07:38 UTC, TarasOrlovskyi approved these changes

2021-10-04 19:22 UTC, merged